### ISSUE TITLE
Could not find property 'bintray_user'

### ISSUE THREAD

**Issue by Kiarasht** [spongebobrf/MaterialIntroTutorial#1]
Hey I'm getting this issue with the gradle

> Restart@RESTART32 /C/Users/Restart/AndroidStudioProjects/MaterialIntroTutorial (master)
> $ ./gradlew build
> 
> FAILURE: Build failed with an exception.
> - Where:
>   Build file 'C:\Users\Restart\AndroidStudioProjects\MaterialIntroTutorial\materialhelptutorial\build.gradle' line: 40
> - What went wrong:
>   A problem occurred evaluating project ':materialhelptutorial'.
>   Could not find property 'BINTRAY_USER' on com.jfrog.bintray.gradle.BintrayExtension_Decorated@27976390.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 3.849 secs

**Comment by riggaroo** [comment]
Hi there,
I have fixed this in commit 
https://github.com/spongebobrf/MaterialIntroTutorial/commit/cf55dd3dc0b994f2e839b09da5508d6974423d1c

Please try again and let me know if its working.

**Comment by Kiarasht** [comment]
Thanks, it's working now.
