### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by lolobosse** [spongebobrf/MaterialIntroTutorial#10]
Hey, actually better than having

`compile 'za.co.riggaroo:materialhelptutorial:1.1.0'`

it would maybe make more sense to have:

`compile 'za.co.riggaroo:materialhelptutorial:1.+'`

So that the compatibility for 11+ is out of the box and you do not need to update the readme for every version

**Comment by riggaroo** [comment]
Hi,
Updated.
