### ISSUE TITLE
How to change text of next and dine button ?

### ISSUE THREAD

**Issue by davoodkaz** [spongebobrf/MaterialIntroTutorial#17]
Hi 
Thanks for your nice intro 
could you help me how to change text of the buttons ?
best regards

**Comment by riggaroo** [comment]
Hi there,
In your strings.xml, add the following strings with the same name:

```
    <string name="tutorial_done">DONE</string>
    <string name="tutorial_skip">SKIP</string>
```


You can then change the text in your app to the text you desire, this will overwrite the ones in the library.

**Comment by davoodkaz** [comment]
hi
thanks a lot
i have done it
