### ISSUE TITLE
Add support for Picasso

### ISSUE THREAD

**Issue by MohMah** [spongebobrf/MaterialIntroTutorial#3]
Hi, 
As you know Glide's method count is much bigger than Picasso and not everyone can use it so please add Picasso support. 
thanks

**Comment by riggaroo** [comment]
Hi MohMah,

It is quite easy to switch to Picasso if you wish to. It is only being used for loading the tutorial images. 
You are welcome to fork the code and switch to Picasso. I will be sticking with Glide for a while as my other apps are using it.

You can also enable mutlidex if you are having method count issues.
http://developer.android.com/tools/building/multidex.html
