### ISSUE TITLE
A few requests

### ISSUE THREAD

**Issue by yigitserin** [spongebobrf/MaterialIntroTutorial#4]
Hello there, I would like to use this, but need a few more features. I will try to implement if I have time later but if you can, here they are:
- An option to change text colors. Including title, subtitle and activity buttons (skip and done)
- An option to localize skip and done buttons. 

That's it for now. It's looking good and hope you can implement these features. 
Thanks!

**Comment by riggaroo** [comment]
Hi yigitserin,

I have changed the text colors not to be hardcoded anymore. Upgrade to 1.1.0, and then in your colors.xml file, you will need to override the following if you want different colours:

```
 <color name="tutorial_buttonTextColor">#ffffff</color>
    <color name="tutorial_subtitleTextColor">#ffffff</color>
    <color name="tutorial_titleTextColor">#ffffff</color>
```

With your own colours. The same can be done for the localisation of the done and skip buttons.

```
  <string name="tutorial_done">DONE</string>
    <string name="tutorial_skip">SKIP</string>
```

**Comment by yigitserin** [comment]
Great thanks!
